'use client';

import React, { useState, useMemo, useEffect } from 'react';
import { ALL_SERVICE_RESPONSES, type ServiceResponseItem } from '@/lib/datasetLoader';
import { fillChaosPayload } from '@/utilities/chaos-data/chaosTemplateFiller';
import { 
  Radio, 
  Search, 
  Copy, 
  CheckCircle2, 
  ExternalLink, 
  Code2, 
  RefreshCw, 
  Sparkles, 
  Flame, 
  Sliders, 
  ShieldAlert,
  Terminal,
  FileJson
} from 'lucide-react';

export function ChaosTemplatesClient() {
  const [selectedServiceId, setSelectedServiceId] = useState<string>(ALL_SERVICE_RESPONSES[0].id);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [activeResponseKey, setActiveResponseKey] = useState<string>('');
  const [entropy, setEntropy] = useState<number>(75);
  const [viewMode, setViewMode] = useState<'chaos' | 'clean' | 'typescript' | 'curl'>('chaos');
  const [seed, setSeed] = useState<number>(0);
  const [simulatedStatus, setSimulatedStatus] = useState<number>(200);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  // Re-roll hotkey R
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.key === 'r' || e.key === 'R') && !['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement).tagName)) {
        setSeed(s => s + 1);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const categories = [
    { id: 'All', label: 'All 17 Templates' },
    { id: 'auth_and_sso', label: 'Auth & SSO' },
    { id: 'ecommerce_and_b2b', label: 'E-Commerce & B2B' },
    { id: 'developer_and_cloud', label: 'Cloud & APIs' },
    { id: 'schemas', label: 'Standards & Schemas' },
  ];

  const filteredServices = useMemo(() => {
    return ALL_SERVICE_RESPONSES.filter(svc => {
      const matchesCategory = selectedCategory === 'All' || svc.category === selectedCategory;
      const q = searchQuery.toLowerCase();
      const matchesSearch = 
        !q ||
        svc.service.toLowerCase().includes(q) || 
        svc.provider.toLowerCase().includes(q) ||
        svc.id.toLowerCase().includes(q);
      return matchesCategory && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const activeService = useMemo(() => {
    return ALL_SERVICE_RESPONSES.find(s => s.id === selectedServiceId) || ALL_SERVICE_RESPONSES[0];
  }, [selectedServiceId]);

  // Available responses in the selected service
  const responseKeys = useMemo(() => {
    if (!activeService.responses) return [];
    return Object.keys(activeService.responses);
  }, [activeService]);

  const currentResponseKey = activeResponseKey && responseKeys.includes(activeResponseKey) 
    ? activeResponseKey 
    : responseKeys[0] || '';

  const activeResponseObj = activeService.responses?.[currentResponseKey];

  // Clean original payload
  const cleanPayload = useMemo(() => {
    return activeResponseObj?.payload || activeService.payload || { message: "Standard service payload" };
  }, [activeResponseObj, activeService]);

  // Chaos-filled dirty payload generated by chaos engine
  const chaosPayload = useMemo(() => {
    void seed;
    if (simulatedStatus === 400) {
      return {
        type: "https://errors.api.io/bad-request",
        title: "Bad Request — Schema Failure",
        status: 400,
        detail: "The request payload failed validation against the chaos schema constraints.",
        instance: `/requests/req_${Math.random().toString(36).substring(2, 9)}`,
        invalid_parameters: [
          { name: "token", reason: "Value contained zero-width Unicode injection" },
          { name: "email", reason: "Invalid punycode domain formatting" }
        ]
      };
    }
    if (simulatedStatus === 401) {
      return {
        error: "invalid_client_credentials",
        error_description: "Client authentication token revoked or expired.",
        status: 401
      };
    }
    if (simulatedStatus === 429) {
      return {
        error: "rate_limit_exceeded",
        message: "You have exceeded the maximum request quota (100 requests/min).",
        retry_after_seconds: 42,
        status: 429
      };
    }
    if (simulatedStatus === 500) {
      return {
        error: "internal_server_error",
        message: "Upstream identity provider returned malformed JSON response.",
        incident_id: `inc_${Math.random().toString(36).substring(2, 9)}`,
        status: 500
      };
    }

    return fillChaosPayload(cleanPayload, entropy);
  }, [cleanPayload, entropy, seed, simulatedStatus]);

  // Active payload depending on mode
  const activeDisplayPayload = viewMode === 'clean' ? cleanPayload : chaosPayload;

  // TypeScript interface generator
  const generatedTypeScript = useMemo(() => {
    const inferType = (val: any): string => {
      if (val === null) return 'string | null';
      if (typeof val === 'number') return 'number';
      if (typeof val === 'boolean') return 'boolean';
      if (Array.isArray(val)) {
        if (val.length === 0) return 'any[]';
        return `${inferType(val[0])}[]`;
      }
      if (typeof val === 'object') return 'Record<string, any>';
      return 'string';
    };

    const typeName = activeService.service.replace(/[^a-zA-Z0-9]/g, '') + 'Fixture';
    const fields = Object.entries(activeDisplayPayload)
      .map(([k, v]) => `  ${k}: ${inferType(v)};`)
      .join('\n');

    return `export interface ${typeName} {\n${fields}\n}\n\n// Chaos-Injected Test Fixture:\nexport const CHAOS_${typeName.toUpperCase()}: ${typeName} = ${JSON.stringify(activeDisplayPayload, null, 2)};`;
  }, [activeDisplayPayload, activeService]);

  // cURL generator
  const generatedCurl = useMemo(() => {
    const endpointUrl = activeService.endpoints ? Object.values(activeService.endpoints)[0] : 'https://api.service.com/v1/endpoint';
    return `curl -X POST "${endpointUrl}" \\
  -H "Authorization: Bearer ${(chaosPayload.access_token || 'sample_chaos_token_' + Date.now()).slice(0, 32)}" \\
  -H "Content-Type: application/json" \\
  -d '${JSON.stringify(chaosPayload).slice(0, 150)}...'`;
  }, [activeService, chaosPayload]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(id);
    setTimeout(() => setCopiedCode(null), 1800);
  };

  const getStatusColor = (status: number) => {
    if (status >= 200 && status < 300) return 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-300 border-emerald-500/30';
    if (status === 429) return 'bg-amber-500/15 text-amber-600 dark:text-amber-300 border-amber-500/30';
    return 'bg-rose-500/15 text-rose-600 dark:text-rose-300 border-rose-500/30';
  };

  return (
    <div className="h-full flex flex-col md:flex-row p-3 overflow-hidden gap-3 font-mono">
      {/* Left Sidebar: 17 Real Service Templates */}
      <div className="w-full md:w-80 bg-[var(--bg-panel)] border border-[var(--border-dev)] rounded-xl flex flex-col overflow-hidden shrink-0 shadow-sm transition-colors">
        {/* Header & Search */}
        <div className="p-3 border-b border-[var(--border-dev)] flex flex-col gap-2 bg-[var(--bg-panel-subtle)] shrink-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Flame className="w-4 h-4 text-rose-500" />
              <span className="text-xs font-bold text-[var(--text-primary)] font-sans uppercase">API Chaos Templates</span>
            </div>
            <span className="text-[10px] px-1.5 py-0.2 rounded bg-[var(--pill-bg)] text-rose-500 font-bold">
              17 Services
            </span>
          </div>

          <div className="flex items-center gap-2">
            <Search className="w-3.5 h-3.5 text-[var(--text-muted)]" />
            <input
              type="text"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search templates (Google, Stripe, Supabase...)"
              className="dev-input flex-1 px-2 py-1 rounded text-xs"
            />
          </div>

          <select
            value={selectedCategory}
            onChange={e => setSelectedCategory(e.target.value)}
            className="dev-input px-2 py-1 rounded text-xs bg-[var(--bg-sidebar)]"
          >
            {categories.map(c => (
              <option key={c.id} value={c.id}>{c.label}</option>
            ))}
          </select>
        </div>

        {/* Templates List */}
        <div className="flex-1 overflow-y-auto p-2 flex flex-col gap-1.5">
          {filteredServices.map(svc => {
            const isSelected = svc.id === selectedServiceId;
            return (
              <button
                key={svc.id}
                onClick={() => {
                  setSelectedServiceId(svc.id);
                  setActiveResponseKey('');
                  setSimulatedStatus(200);
                }}
                className={`w-full text-left p-2.5 rounded-lg border transition-all flex flex-col gap-1 cursor-pointer ${
                  isSelected 
                    ? 'bg-[var(--bg-sidebar)] border-rose-500 shadow-sm' 
                    : 'border-transparent hover:bg-[var(--bg-sidebar)]/60 text-[var(--text-secondary)]'
                }`}
              >
                <div className="flex items-center justify-between gap-1">
                  <span className={`text-xs font-bold font-sans truncate ${isSelected ? 'text-rose-500' : 'text-[var(--text-primary)]'}`}>
                    {svc.service}
                  </span>
                </div>
                <div className="text-[10px] text-[var(--text-muted)] truncate flex items-center justify-between">
                  <span>{svc.provider}</span>
                  <span className="font-bold opacity-75">{svc.categoryTitle}</span>
                </div>
              </button>
            );
          })}
        </div>

        <div className="p-2 border-t border-[var(--border-dev)] text-[10px] text-[var(--text-muted)] text-center bg-[var(--bg-panel-subtle)]">
          <strong>{filteredServices.length}</strong> real-world production schemas
        </div>
      </div>

      {/* Main Workbench: Chaos Template Generator */}
      <div className="flex-1 flex flex-col gap-3 min-w-0 overflow-hidden">
        {/* Template Header & Sliders */}
        <div className="bg-[var(--bg-panel)] border border-[var(--border-dev)] rounded-xl p-4 shrink-0 shadow-sm transition-colors flex flex-col gap-3">
          <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-[var(--border-dev)]">
            <div>
              <div className="flex items-center gap-2.5">
                <h2 className="text-base font-bold text-[var(--text-primary)] font-sans">
                  {activeService.service}
                </h2>
                <span className="text-[10px] px-2 py-0.5 rounded font-bold bg-[var(--pill-bg)] border border-[var(--border-dev)] text-[var(--text-muted)]">
                  {activeService.provider}
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded font-bold bg-rose-500/15 text-rose-500 border border-rose-500/30">
                  Chaos Injected
                </span>
              </div>
              <div className="text-xs text-[var(--text-secondary)] font-sans mt-0.5">
                {activeResponseObj?.description || activeService.description || 'Production API response filled with high-entropy edge case test values.'}
              </div>
            </div>

            {/* Re-roll and Links */}
            <div className="flex items-center gap-2">
              <button
                onClick={() => setSeed(s => s + 1)}
                className="px-3 py-1 text-xs font-bold rounded bg-rose-500 text-white hover:bg-rose-600 flex items-center gap-1.5 transition-colors shadow-sm shadow-rose-500/20 cursor-pointer"
                title="Re-roll chaos values (Hotkey: [R])"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Re-roll (R)</span>
              </button>

              {activeService.documentation_url && (
                <a
                  href={activeService.documentation_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2.5 py-1 text-xs font-semibold rounded bg-[var(--bg-sidebar)] border border-[var(--border-dev)] text-[var(--text-primary)] hover:border-rose-500 flex items-center gap-1.5 transition-colors"
                >
                  <span>Docs</span>
                  <ExternalLink className="w-3.5 h-3.5 text-rose-500" />
                </a>
              )}
            </div>
          </div>

          {/* Chaos Sliders & Mode Switcher */}
          <div className="flex flex-wrap items-center justify-between gap-3 text-xs">
            <div className="flex flex-wrap items-center gap-3">
              {/* Entropy Slider */}
              <div className="flex items-center gap-1.5 bg-[var(--bg-sidebar)] px-2.5 py-1 rounded border border-[var(--border-dev)]">
                <span className="text-[10px] text-[var(--text-muted)] flex items-center gap-1">
                  <Flame className="w-3 h-3 text-rose-500" />
                  <span>CHAOS ENTROPY:</span>
                </span>
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={entropy}
                  onChange={e => setEntropy(Number(e.target.value))}
                  className="w-20 accent-rose-500 cursor-pointer h-1"
                />
                <span className="text-[10px] font-bold text-rose-500 w-8 text-right">{entropy}%</span>
              </div>

              {/* Response Sub-type Selector */}
              {responseKeys.length > 1 && (
                <div className="flex items-center gap-1 bg-[var(--bg-sidebar)] p-0.5 rounded border border-[var(--border-dev)]">
                  <span className="text-[10px] text-[var(--text-muted)] px-1.5">RESPONSE:</span>
                  {responseKeys.map(key => (
                    <button
                      key={key}
                      onClick={() => {
                        setActiveResponseKey(key);
                        setSimulatedStatus(200);
                      }}
                      className={`px-2 py-0.5 rounded text-[11px] transition-colors cursor-pointer ${
                        currentResponseKey === key
                          ? 'bg-rose-500 text-white font-bold'
                          : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                      }`}
                    >
                      {key.replace(/_/g, ' ')}
                    </button>
                  ))}
                </div>
              )}

              {/* Status Code Simulator */}
              <div className="flex items-center gap-1 bg-[var(--bg-sidebar)] p-0.5 rounded border border-[var(--border-dev)]">
                <span className="text-[10px] text-[var(--text-muted)] px-1.5">STATUS:</span>
                {[200, 400, 401, 429, 500].map(st => (
                  <button
                    key={st}
                    onClick={() => setSimulatedStatus(st)}
                    className={`px-1.5 py-0.5 rounded text-[10px] font-bold transition-colors cursor-pointer ${
                      simulatedStatus === st
                        ? (st === 200 ? 'bg-emerald-500 text-white' : 'bg-rose-500 text-white')
                        : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                    }`}
                  >
                    {st}
                  </button>
                ))}
              </div>
            </div>

            {/* View Mode Switcher & Copy */}
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1 bg-[var(--bg-sidebar)] p-0.5 rounded border border-[var(--border-dev)]">
                {(['chaos', 'clean', 'typescript', 'curl'] as const).map(mode => (
                  <button
                    key={mode}
                    onClick={() => setViewMode(mode)}
                    className={`px-2 py-0.5 rounded text-[11px] uppercase transition-colors cursor-pointer ${
                      viewMode === mode
                        ? 'bg-black/15 dark:bg-white/15 text-rose-500 font-bold'
                        : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'
                    }`}
                  >
                    {mode === 'chaos' ? '⚡ Chaos Payload' : mode}
                  </button>
                ))}
              </div>

              <button
                onClick={() => {
                  const textToCopy = 
                    viewMode === 'typescript' ? generatedTypeScript :
                    viewMode === 'curl' ? generatedCurl :
                    JSON.stringify(activeDisplayPayload, null, 2);
                  copyToClipboard(textToCopy, 'main-copy');
                }}
                className="px-2.5 py-1 text-xs font-semibold rounded bg-[var(--bg-sidebar)] border border-[var(--border-dev)] text-[var(--text-primary)] hover:border-rose-500 flex items-center gap-1 transition-colors cursor-pointer"
              >
                {copiedCode === 'main-copy' ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-rose-500" />}
                <span>{copiedCode === 'main-copy' ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Output Code Viewer */}
        <div className="flex-1 min-h-0 bg-[var(--bg-panel)] border border-[var(--border-dev)] rounded-xl overflow-hidden flex flex-col shadow-sm">
          <div className="px-4 py-2 border-b border-[var(--border-dev)] flex items-center justify-between text-xs bg-[var(--bg-panel-subtle)] shrink-0">
            <div className="flex items-center gap-2">
              <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getStatusColor(simulatedStatus)}`}>
                HTTP {simulatedStatus} {simulatedStatus === 200 ? 'OK' : simulatedStatus === 429 ? 'Rate Limited' : 'Error'}
              </span>
              <span className="text-[var(--text-muted)] text-[11px]">
                mode: <strong className="text-rose-500">{viewMode}</strong>
              </span>
            </div>

            <div className="text-[11px] text-[var(--text-muted)]">
              size: <strong className="text-cyan-500">{(new TextEncoder().encode(JSON.stringify(activeDisplayPayload)).length / 1024).toFixed(1)} KB</strong>
            </div>
          </div>

          <div className="flex-1 overflow-auto p-4 bg-[var(--bg-codebox)] font-mono text-xs leading-relaxed text-[var(--text-code)]">
            {viewMode === 'typescript' ? (
              <pre className="m-0 text-cyan-300">
                <code>{generatedTypeScript}</code>
              </pre>
            ) : viewMode === 'curl' ? (
              <pre className="m-0 text-emerald-400">
                <code>{generatedCurl}</code>
              </pre>
            ) : (
              <pre className="m-0">
                <code>{JSON.stringify(activeDisplayPayload, null, 2)}</code>
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
